name: Fetch Google Sheet Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client

    - name: Fetch and save data
      run: python fetch_data.py
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        SHEET_URL: ${{ secrets.SHEET_URL }}
        VERSION_FILE_PATH: ${{ secrets.VERSION_FILE_PATH }}

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update english.csv"
        git push
        
    - name: Create releases directory
      run: mkdir releases

    - name: Create dos_sammul release
      run: zip -r dos_sammul.zip "${{ secrets.VERSION_FILE_PATH }}/dossammul"
      working-directory: releases/

    - name: Create galmuri9 release
      run: zip -r galmuri9.zip "${{ secrets.VERSION_FILE_PATH }}/galmuri9"
      working-directory: releases/

    - name: Create neodgm release
      run: zip -r neodgm.zip "${{ secrets.VERSION_FILE_PATH }}/neodgm"
      working-directory: releases/

    - name: Create release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files:
          - dos_sammul.zip
          - galmuri9.zip
          - neodgm.zip
        token: ${{ secrets.WORKFLOW_TOKEN }}
        tag_name: v1.0
        title: Translation files for v1.0
        body: |
          Translation files for v1.0 release.
