name: Fetch Google Sheet Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client

    - name: Fetch and save data
      run: python fetch_data.py
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        SHEET_URL: ${{ secrets.SHEET_URL }}
        VERSION_FILE_PATH: ${{ secrets.VERSION_FILE_PATH }}

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/VR-Games-Korean-Translate/Ancient_Dungeon_Korean_Translate.git
        git add .
        git commit -m "Update english.csv"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
